version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot_backend
    env_file:
      - .env
    # Expose 8000 en interne pour le réseau Docker
    expose:
      - "8000"
    networks:
      - chatbot_net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: chatbot_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Vous devez lier vos certificats si vous les avez localement
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - chatbot_net

networks:
  chatbot_net:
    driver: bridge
